=== tfrayner/clinstudyweb/trunk/schema/clindb_admin.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- Basic data types -->

  <xs:simpleType name="varcharType">
    <xs:restriction base="xs:string">
      <xs:maxLength value="255"/>
      <xs:minLength value="1"/>
      <xs:whiteSpace value="collapse"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="passHashType">
    <xs:restriction base="xs:string">
      <xs:maxLength value="40"/>
      <xs:minLength value="1"/>
      <xs:whiteSpace value="collapse"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- This is not ideal as it doesn't detect invalid dates;
  xs:dateTime requires a slightly different format though -->
  <xs:simpleType name="dateType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- Types corresponding to database tables -->

  <xs:complexType name="controlledVocabType">
    <xs:attribute name="category" type="varcharType" use="required"/>
    <xs:attribute name="value" type="varcharType" use="required"/>
  </xs:complexType>

  <xs:complexType name="testType">
    <xs:sequence>
      <xs:element name="TestPossibleValues" type="testPossibleValueGroup" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="name" type="varcharType" use="required"/>
  </xs:complexType>

  <xs:complexType name="testPossibleValueType">
    <xs:attribute name="category" type="varcharType" use="required"/>
    <xs:attribute name="value" type="varcharType" use="required"/>
  </xs:complexType>

  <xs:complexType name="roleType">
    <xs:attribute name="role" type="varcharType" use="required"/>
  </xs:complexType>

  <xs:complexType name="userType">
    <xs:sequence>
      <xs:element name="UserRoles" type="roleGroup" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="username" type="varcharType" use="required"/>
    <xs:attribute name="name" type="varcharType"/>
    <xs:attribute name="email" type="varcharType"/>
    <xs:attribute name="password" type="passHashType" use="required"/>
    <xs:attribute name="date_created" type="dateType"/>
    <xs:attribute name="date_modified" type="dateType"/>
    <xs:attribute name="date_accessed" type="dateType"/>
  </xs:complexType>

  <!-- Node group types -->

  <xs:complexType name="controlledVocabGroup">
    <xs:sequence>
      <xs:element name="ControlledVocab" type="controlledVocabType" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="testGroup">
    <xs:sequence>
      <xs:element name="Test" type="testType" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="testPossibleValueGroup">
    <xs:sequence>
      <xs:element name="TestPossibleValue" type="testPossibleValueType" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="userGroup">
    <xs:sequence>
      <xs:element name="User" type="userType" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="roleGroup">
    <xs:sequence>
      <xs:element name="UserRole" type="roleType" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <!-- Document root element and global unique key fields -->

  <xs:element name="ClinStudyAdminML">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ControlledVocabs" type="controlledVocabGroup" minOccurs="0"/>
        <xs:element name="Tests" type="testGroup" minOccurs="0"/>
        <xs:element name="Users" type="userGroup" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
    <xs:unique name="userName">
      <xs:selector xpath=".//User"/>
      <xs:field xpath="@username"/>
    </xs:unique>
    <xs:key name="controlledVocabKey">
      <xs:selector xpath=".//ControlledVocab"/>
      <xs:field xpath="@category"/>
      <xs:field xpath="@value"/>
    </xs:key>
    <xs:keyref name="controlledVocabKeyRef" refer="controlledVocabKey">
      <xs:selector xpath=".//TestPossibleValue"/>
      <xs:field xpath="@category"/>
      <xs:field xpath="@value"/>
    </xs:keyref>
  </xs:element>

</xs:schema>

=== tfrayner/clinstudyweb/trunk/schema/default_semantic_framework.xml
<?xml version="1.0"?>
<ClinStudyAdminML xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="clindb_admin.xsd">
  <ControlledVocabs>
    <ControlledVocab category="AdverseAction" value="Dosage changed"/>
    <ControlledVocab category="AdverseAction" value="Drug changed or stopped"/>
    <ControlledVocab category="AdverseAction" value="Drug started"/>
    <ControlledVocab category="AdverseAction" value="Hospitalisation"/>
    <ControlledVocab category="AdverseAction" value="Non-drug therapy"/>
    <ControlledVocab category="AdverseAction" value="None"/>
    <ControlledVocab category="AdverseAction" value="Permanent stoppage"/>
    <ControlledVocab category="AdverseAction" value="Temporary stoppage"/>
    <ControlledVocab category="AdverseOutcome" value="Condition improving"/>
    <ControlledVocab category="AdverseOutcome" value="Condition unchanged"/>
    <ControlledVocab category="AdverseOutcome" value="Condition worsening"/>
    <ControlledVocab category="AdverseOutcome" value="Death due to this AE"/>
    <ControlledVocab category="AdverseOutcome" value="Full recovery"/>
    <ControlledVocab category="AdverseOutcome" value="Recovery with sequelae"/>
    <ControlledVocab category="AdverseSeverity" value="Life threatening"/>
    <ControlledVocab category="AdverseSeverity" value="Mild"/>
    <ControlledVocab category="AdverseSeverity" value="Moderate"/>
    <ControlledVocab category="AdverseSeverity" value="Severe"/>
    <ControlledVocab category="AdverseTrialRelated" value="Highly probable"/>
    <ControlledVocab category="AdverseTrialRelated" value="Possible"/>
    <ControlledVocab category="AdverseTrialRelated" value="Probable"/>
    <ControlledVocab category="AdverseTrialRelated" value="Unlikely"/>
    <ControlledVocab category="AdverseTrialRelated" value="Unrelated"/>
    <ControlledVocab category="CellType" value="CD14"/>
    <ControlledVocab category="CellType" value="CD16"/>
    <ControlledVocab category="CellType" value="CD19"/>
    <ControlledVocab category="CellType" value="CD4"/>
    <ControlledVocab category="CellType" value="CD8"/>
    <ControlledVocab category="CellType" value="naive CD8"/>
    <ControlledVocab category="CellType" value="none"/>
    <ControlledVocab category="CellType" value="PBMC"/>
    <ControlledVocab category="CellType" value="unknown"/>
    <ControlledVocab category="ClinicalFeature" value="Anaemia"/>
    <ControlledVocab category="ClinicalFeature" value="Antinuclear antibodies"/>
    <ControlledVocab category="ClinicalFeature" value="Arthritis"/>
    <ControlledVocab category="ClinicalFeature" value="Depression"/>
    <ControlledVocab category="ClinicalFeature" value="Discoid rash"/>
    <ControlledVocab category="ClinicalFeature" value="Fatigue"/>
    <ControlledVocab category="ClinicalFeature" value="Haematologic disorder"/>
    <ControlledVocab category="ClinicalFeature" value="Immunologic disorder"/>
    <ControlledVocab category="ClinicalFeature" value="Insomnia"/>
    <ControlledVocab category="ClinicalFeature" value="Malar rash"/>
    <ControlledVocab category="ClinicalFeature" value="Neurologic disorders"/>
    <ControlledVocab category="ClinicalFeature" value="Oral Ulcers"/>
    <ControlledVocab category="ClinicalFeature" value="Photosensitivity"/>
    <ControlledVocab category="ClinicalFeature" value="Renal disorder"/>
    <ControlledVocab category="ClinicalFeature" value="Serositis"/>
    <ControlledVocab category="DiagnosisCondition" value="ADPKD"/>
    <ControlledVocab category="DiagnosisCondition" value="Behcet's Syndrome"/>
    <ControlledVocab category="DiagnosisCondition" value="Bilateral small kidneys"/>
    <ControlledVocab category="DiagnosisCondition" value="Cerebral vasculitis/Lymphoma"/>
    <ControlledVocab category="DiagnosisCondition" value="Chronic PN"/>
    <ControlledVocab category="DiagnosisCondition" value="Churg Strauss Syndrome"/>
    <ControlledVocab category="DiagnosisCondition" value="Congenital renal dysplasia"/>
    <ControlledVocab category="DiagnosisCondition" value="Crohn's disease"/>
    <ControlledVocab category="DiagnosisCondition" value="Cryoglobulinaemia"/>
    <ControlledVocab category="DiagnosisCondition" value="Diabetes"/>
    <ControlledVocab category="DiagnosisCondition" value="Easonophine vasculitis"/>
    <ControlledVocab category="DiagnosisCondition" value="Giant Cell Arteritis"/>
    <ControlledVocab category="DiagnosisCondition" value="Goodpasture's Syndrome"/>
    <ControlledVocab category="DiagnosisCondition" value="Henoch-Schonlein Purpura"/>
    <ControlledVocab category="DiagnosisCondition" value="Hypertension"/>
    <ControlledVocab category="DiagnosisCondition" value="IgA Nephropathy"/>
    <ControlledVocab category="DiagnosisCondition" value="Lithium nephrotoxicity"/>
    <ControlledVocab category="DiagnosisCondition" value="MCGN Type 1"/>
    <ControlledVocab category="DiagnosisCondition" value="MCGN Type 2"/>
    <ControlledVocab category="DiagnosisCondition" value="Membranous nephropathy"/>
    <ControlledVocab category="DiagnosisCondition" value="Microscopic Polyangiitis"/>
    <ControlledVocab category="DiagnosisCondition" value="Multiple sclerosis"/>
    <ControlledVocab category="DiagnosisCondition" value="Obstructive uropathy"/>
    <ControlledVocab category="DiagnosisCondition" value="Polyarteritis Nodosa"/>
    <ControlledVocab category="DiagnosisCondition" value="Posterior urethral valves/Obstruction"/>
    <ControlledVocab category="DiagnosisCondition" value="Reflux Nephropathy"/>
    <ControlledVocab category="DiagnosisCondition" value="Rheumatoid arthritis"/>
    <ControlledVocab category="DiagnosisCondition" value="Schnitzler syndrome"/>
    <ControlledVocab category="DiagnosisCondition" value="Sjogren's syndrome"/>
    <ControlledVocab category="DiagnosisCondition" value="Systemic Lupus Erythematosus"/>
    <ControlledVocab category="DiagnosisCondition" value="Takayasu's Arteritis"/>
    <ControlledVocab category="DiagnosisCondition" value="Transplant"/>
    <ControlledVocab category="DiagnosisCondition" value="Ulcerative colitis"/>
    <ControlledVocab category="DiagnosisCondition" value="Urinary stone disease"/>
    <ControlledVocab category="DiagnosisCondition" value="Vasculitic Rash"/>
    <ControlledVocab category="DiagnosisCondition" value="Vasculitis"/>
    <ControlledVocab category="DiagnosisCondition" value="Wegener's Granulomatosis"/>
    <ControlledVocab category="DiagnosisConfidence" value="Definite"/>
    <ControlledVocab category="DiagnosisConfidence" value="Possible"/>
    <ControlledVocab category="DiagnosisConfidence" value="Probable"/>
    <ControlledVocab category="DiseaseActivity" value="Active disease/Flare"/>
    <ControlledVocab category="DiseaseActivity" value="Low-grade activity"/>
    <ControlledVocab category="DiseaseActivity" value="No activity"/>
    <ControlledVocab category="DiseaseActivity" value="Remission"/>
    <ControlledVocab category="DiseaseEventType" value="relapse"/>
    <ControlledVocab category="DiseaseEventType" value="remission"/>
    <ControlledVocab category="DonorType" value="Cadaveric Asystolic"/>
    <ControlledVocab category="DonorType" value="Cadaveric Heart Beating"/>
    <ControlledVocab category="DonorType" value="Live Related"/>
    <ControlledVocab category="DonorType" value="Live Unrelated"/>
    <ControlledVocab category="DoseFrequency" value="1x / month"/>
    <ControlledVocab category="DoseFrequency" value="1x / wk"/>
    <ControlledVocab category="DoseFrequency" value="2x / month"/>
    <ControlledVocab category="DoseFrequency" value="2x / wk"/>
    <ControlledVocab category="DoseFrequency" value="3x / month"/>
    <ControlledVocab category="DoseFrequency" value="3x / wk"/>
    <ControlledVocab category="DoseFrequency" value="5x / day"/>
    <ControlledVocab category="DoseFrequency" value="6x / day"/>
    <ControlledVocab category="DoseFrequency" value="6x / wk"/>
    <ControlledVocab category="DoseFrequency" value="am"/>
    <ControlledVocab category="DoseFrequency" value="bd"/>
    <ControlledVocab category="DoseFrequency" value="od"/>
    <ControlledVocab category="DoseFrequency" value="prn"/>
    <ControlledVocab category="DoseFrequency" value="once"/>
    <ControlledVocab category="DoseFrequency" value="pm"/>
    <ControlledVocab category="DoseFrequency" value="qds"/>
    <ControlledVocab category="DoseFrequency" value="tds"/>
    <ControlledVocab category="DoseUnit" value="gm"/>
    <ControlledVocab category="DoseUnit" value="mcg"/>
    <ControlledVocab category="DoseUnit" value="mg"/>
    <ControlledVocab category="DoseUnit" value="ng"/>
    <ControlledVocab category="DoseUnit" value="tabs"/>
    <ControlledVocab category="DrugLocale" value="in clinic"/>
    <ControlledVocab category="DrugLocale" value="prescription"/>
    <ControlledVocab category="DrugType" value="immunosuppression"/>
    <ControlledVocab category="DrugType" value="other"/>
    <ControlledVocab category="Ethnicity" value="Asian"/>
    <ControlledVocab category="Ethnicity" value="Black"/>
    <ControlledVocab category="Ethnicity" value="Caucasian"/>
    <ControlledVocab category="Ethnicity" value="Hispanic"/>
    <ControlledVocab category="HomeCentre" value="Cambridge"/>
    <ControlledVocab category="HomeCentre" value="Oxford"/>
    <ControlledVocab category="HomeCentre" value="Singapore"/>
    <ControlledVocab category="HomeCentre" value="Singapore SGH"/>
    <ControlledVocab category="LabelCompound" value="biotin"/>
    <ControlledVocab category="LabelCompound" value="Cy3"/>
    <ControlledVocab category="LabelCompound" value="Cy5"/>
    <ControlledVocab category="MaterialType" value="cDNA"/>
    <ControlledVocab category="MaterialType" value="genomic DNA"/>
    <ControlledVocab category="MaterialType" value="plasma"/>
    <ControlledVocab category="MaterialType" value="RNA"/>
    <ControlledVocab category="MaterialType" value="serum"/>
    <ControlledVocab category="NominalTimepoint" value="0 months"/>
