=== tfrayner/clinstudyweb/schema/clindb_admin.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- Basic data types -->

  <xs:simpleType name="varcharType">
    <xs:restriction base="xs:string">
      <xs:maxLength value="255"/>
      <xs:minLength value="1"/>
      <xs:whiteSpace value="collapse"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="shortvarcharType">
    <xs:restriction base="xs:string">
      <xs:maxLength value="31"/>
      <xs:minLength value="1"/>
      <xs:whiteSpace value="collapse"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="passHashType">
    <xs:restriction base="xs:string">
      <xs:maxLength value="40"/>
      <xs:minLength value="1"/>
      <xs:whiteSpace value="collapse"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- This is not ideal as it doesn't detect invalid dates;
  xs:dateTime requires a slightly different format though -->
  <xs:simpleType name="dateType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- Types corresponding to database tables -->

  <xs:complexType name="controlledVocabType">
    <xs:sequence>
      <xs:element name="RelatedVocabs" type="relatedVocabGroup" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="accession" type="shortvarcharType" use="required"/>
    <xs:attribute name="category" type="varcharType" use="required"/>
    <xs:attribute name="value" type="varcharType" use="required"/>
    <xs:attribute name="term_source_ref" type="shortvarcharType"/>
  </xs:complexType>

  <xs:complexType name="relatedVocabType">
    <xs:attribute name="target_ref" type="shortvarcharType" use="required"/>
    <xs:attribute name="relationship_ref" type="shortvarcharType" use="required"/>
  </xs:complexType>

  <xs:complexType name="termSourceType">
    <xs:attribute name="name" type="shortvarcharType" use="required"/>
    <xs:attribute name="version" type="shortvarcharType"/>
    <xs:attribute name="uri" type="varcharType"/>
  </xs:complexType>

  <xs:complexType name="testType">
    <xs:sequence>
      <xs:element name="TestPossibleValues" type="testPossibleValueGroup" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="name" type="varcharType" use="required"/>
  </xs:complexType>

  <xs:complexType name="testPossibleValueType">
    <xs:attribute name="category" type="varcharType" use="required"/>
    <xs:attribute name="value" type="varcharType" use="required"/>
  </xs:complexType>

  <xs:complexType name="roleType">
    <xs:attribute name="role" type="varcharType" use="required"/>
  </xs:complexType>

  <xs:complexType name="userType">
    <xs:sequence>
      <xs:element name="UserRoles" type="roleGroup" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="username" type="varcharType" use="required"/>
    <xs:attribute name="name" type="varcharType"/>
    <xs:attribute name="email" type="varcharType"/>
    <xs:attribute name="password" type="passHashType" use="required"/>
    <xs:attribute name="date_created" type="dateType"/>
    <xs:attribute name="date_modified" type="dateType"/>
    <xs:attribute name="date_accessed" type="dateType"/>
  </xs:complexType>

  <!-- Node group types -->

  <xs:complexType name="controlledVocabGroup">
    <xs:sequence>
      <xs:element name="ControlledVocab" type="controlledVocabType" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="relatedVocabGroup">
    <xs:sequence>
      <xs:element name="RelatedVocab" type="relatedVocabType" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="termSourceGroup">
    <xs:sequence>
      <xs:element name="TermSource" type="termSourceType" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="testGroup">
    <xs:sequence>
      <xs:element name="Test" type="testType" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="testPossibleValueGroup">
    <xs:sequence>
      <xs:element name="TestPossibleValue" type="testPossibleValueType" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="userGroup">
    <xs:sequence>
      <xs:element name="User" type="userType" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="roleGroup">
    <xs:sequence>
      <xs:element name="UserRole" type="roleType" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <!-- Document root element and global unique key fields -->

  <xs:element name="ClinStudyAdminML">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ControlledVocabs" type="controlledVocabGroup" minOccurs="0"/>
        <xs:element name="TermSources" type="termSourceGroup" minOccurs="0"/>
        <xs:element name="Tests" type="testGroup" minOccurs="0"/>
        <xs:element name="Users" type="userGroup" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
    <xs:unique name="userName">
      <xs:selector xpath=".//User"/>
      <xs:field xpath="@username"/>
    </xs:unique>
    <xs:key name="controlledVocabAccession">
      <xs:selector xpath=".//ControlledVocab"/>
      <xs:field xpath="@accession"/>
    </xs:key>
    <xs:key name="termSourceName">
      <xs:selector xpath=".//TermSource"/>
      <xs:field xpath="@name"/>
    </xs:key>
    <xs:key name="controlledVocabKey">
      <xs:selector xpath=".//ControlledVocab"/>
      <xs:field xpath="@category"/>
      <xs:field xpath="@value"/>
    </xs:key>
    <xs:keyref name="controlledVocabKeyRef" refer="controlledVocabKey">
      <xs:selector xpath=".//TestPossibleValue"/>
      <xs:field xpath="@category"/>
      <xs:field xpath="@value"/>
    </xs:keyref>
    <xs:keyref name="relatedVocabTargetKeyRef" refer="controlledVocabAccession">
      <xs:selector xpath=".//RelatedVocab"/>
      <xs:field xpath="@target_ref"/>
    </xs:keyref>
    <xs:keyref name="relatedVocabRelationshipKeyRef" refer="controlledVocabAccession">
      <xs:selector xpath=".//RelatedVocab"/>
      <xs:field xpath="@relationship_ref"/>
    </xs:keyref>
    <xs:keyref name="termSourceKeyRef" refer="termSourceName">
      <xs:selector xpath=".//ControlledVocab"/>
      <xs:field xpath="@term_source_ref"/>
    </xs:keyref>
  </xs:element>

</xs:schema>

=== tfrayner/clinstudyweb/schema/default_semantic_framework.xml
<?xml version="1.0"?>
<ClinStudyAdminML xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="clindb_admin.xsd">
  <ControlledVocabs>
    <ControlledVocab accession="CSW:0000000001" category="CVRelationshipType" value="instance_of"/>
    <ControlledVocab accession="CSW:0000000002" category="CVRelationshipType" value="synonym_of"/>
    <ControlledVocab accession="CSW:0000000003" category="AdverseAction" value="Dosage changed"/>
    <ControlledVocab accession="CSW:0000000004" category="AdverseAction" value="Drug changed or stopped"/>
    <ControlledVocab accession="CSW:0000000005" category="AdverseAction" value="Drug started"/>
    <ControlledVocab accession="CSW:0000000006" category="AdverseAction" value="Hospitalisation"/>
    <ControlledVocab accession="CSW:0000000007" category="AdverseAction" value="Non-drug therapy"/>
    <ControlledVocab accession="CSW:0000000008" category="AdverseAction" value="None"/>
    <ControlledVocab accession="CSW:0000000009" category="AdverseAction" value="Permanent stoppage"/>
    <ControlledVocab accession="CSW:0000000010" category="AdverseAction" value="Temporary stoppage"/>
    <ControlledVocab accession="CSW:0000000011" category="AdverseOutcome" value="Condition improving"/>
    <ControlledVocab accession="CSW:0000000012" category="AdverseOutcome" value="Condition unchanged"/>
    <ControlledVocab accession="CSW:0000000013" category="AdverseOutcome" value="Condition worsening"/>
    <ControlledVocab accession="CSW:0000000014" category="AdverseOutcome" value="Death due to this AE"/>
    <ControlledVocab accession="CSW:0000000015" category="AdverseOutcome" value="Full recovery"/>
    <ControlledVocab accession="CSW:0000000016" category="AdverseOutcome" value="Recovery with sequelae"/>
    <ControlledVocab accession="CSW:0000000017" category="AdverseSeverity" value="Life threatening"/>
    <ControlledVocab accession="CSW:0000000018" category="AdverseSeverity" value="Mild"/>
    <ControlledVocab accession="CSW:0000000019" category="AdverseSeverity" value="Moderate"/>
    <ControlledVocab accession="CSW:0000000020" category="AdverseSeverity" value="Severe"/>
    <ControlledVocab accession="CSW:0000000021" category="AdverseTrialRelated" value="Highly probable"/>
    <ControlledVocab accession="CSW:0000000022" category="AdverseTrialRelated" value="Possible"/>
    <ControlledVocab accession="CSW:0000000023" category="AdverseTrialRelated" value="Probable"/>
    <ControlledVocab accession="CSW:0000000024" category="AdverseTrialRelated" value="Unlikely"/>
    <ControlledVocab accession="CSW:0000000025" category="AdverseTrialRelated" value="Unrelated"/>
    <ControlledVocab accession="CSW:0000000026" category="CellType" value="CD14"/>
    <ControlledVocab accession="CSW:0000000027" category="CellType" value="CD16"/>
    <ControlledVocab accession="CSW:0000000028" category="CellType" value="CD19"/>
    <ControlledVocab accession="CSW:0000000029" category="CellType" value="CD4"/>
    <ControlledVocab accession="CSW:0000000030" category="CellType" value="CD8"/>
    <ControlledVocab accession="CSW:0000000031" category="CellType" value="none"/>
    <ControlledVocab accession="CSW:0000000032" category="CellType" value="PBMC"/>
    <ControlledVocab accession="CSW:0000000033" category="CellType" value="Tcm"/>
    <ControlledVocab accession="CSW:0000000034" category="CellType" value="Tem"/>
    <ControlledVocab accession="CSW:0000000035" category="CellType" value="Temra"/>
    <ControlledVocab accession="CSW:0000000036" category="CellType" value="Tn"/>
    <ControlledVocab accession="CSW:0000000037" category="CellType" value="unknown"/>
    <ControlledVocab accession="CSW:0000000038" category="ClinicalFeature" value="Anaemia"/>
    <ControlledVocab accession="CSW:0000000039" category="ClinicalFeature" value="Antinuclear antibodies"/>
    <ControlledVocab accession="CSW:0000000040" category="ClinicalFeature" value="Arthritis"/>
    <ControlledVocab accession="CSW:0000000041" category="ClinicalFeature" value="Depression"/>
    <ControlledVocab accession="CSW:0000000042" category="ClinicalFeature" value="Discoid rash"/>
    <ControlledVocab accession="CSW:0000000043" category="ClinicalFeature" value="Fatigue"/>
    <ControlledVocab accession="CSW:0000000044" category="ClinicalFeature" value="Haematologic disorder"/>
    <ControlledVocab accession="CSW:0000000045" category="ClinicalFeature" value="Immunologic disorder"/>
    <ControlledVocab accession="CSW:0000000046" category="ClinicalFeature" value="Insomnia"/>
    <ControlledVocab accession="CSW:0000000047" category="ClinicalFeature" value="Malar rash"/>
    <ControlledVocab accession="CSW:0000000048" category="ClinicalFeature" value="Neurologic disorders"/>
    <ControlledVocab accession="CSW:0000000049" category="ClinicalFeature" value="Oral Ulcers"/>
    <ControlledVocab accession="CSW:0000000050" category="ClinicalFeature" value="Photosensitivity"/>
    <ControlledVocab accession="CSW:0000000051" category="ClinicalFeature" value="Renal disorder"/>
    <ControlledVocab accession="CSW:0000000052" category="ClinicalFeature" value="Serositis"/>
    <ControlledVocab accession="CSW:0000000053" category="DiagnosisCondition" value="ADPKD"/>
    <ControlledVocab accession="CSW:0000000054" category="DiagnosisCondition" value="Behcet's Syndrome"/>
    <ControlledVocab accession="CSW:0000000055" category="DiagnosisCondition" value="Bilateral small kidneys"/>
    <ControlledVocab accession="CSW:0000000056" category="DiagnosisCondition" value="Cerebral vasculitis/Lymphoma"/>
    <ControlledVocab accession="CSW:0000000057" category="DiagnosisCondition" value="Chronic PN"/>
    <ControlledVocab accession="CSW:0000000058" category="DiagnosisCondition" value="Churg Strauss Syndrome"/>
    <ControlledVocab accession="CSW:0000000059" category="DiagnosisCondition" value="Congenital renal dysplasia"/>
    <ControlledVocab accession="CSW:0000000060" category="DiagnosisCondition" value="Crohn's disease"/>
    <ControlledVocab accession="CSW:0000000061" category="DiagnosisCondition" value="Cryoglobulinaemia"/>
    <ControlledVocab accession="CSW:0000000062" category="DiagnosisCondition" value="Diabetes"/>
    <ControlledVocab accession="CSW:0000000063" category="DiagnosisCondition" value="Easonophine vasculitis"/>
    <ControlledVocab accession="CSW:0000000064" category="DiagnosisCondition" value="Focal Segmental Glomerulosclerosis"/>
    <ControlledVocab accession="CSW:0000000065" category="DiagnosisCondition" value="Giant Cell Arteritis"/>
    <ControlledVocab accession="CSW:0000000066" category="DiagnosisCondition" value="Goodpasture's Syndrome"/>
    <ControlledVocab accession="CSW:0000000067" category="DiagnosisCondition" value="Henoch-Schonlein Purpura"/>
    <ControlledVocab accession="CSW:0000000068" category="DiagnosisCondition" value="Hypertension"/>
    <ControlledVocab accession="CSW:0000000069" category="DiagnosisCondition" value="IgA Nephropathy"/>
    <ControlledVocab accession="CSW:0000000070" category="DiagnosisCondition" value="Lithium nephrotoxicity"/>
    <ControlledVocab accession="CSW:0000000071" category="DiagnosisCondition" value="MCGN Type 1"/>
    <ControlledVocab accession="CSW:0000000072" category="DiagnosisCondition" value="MCGN Type 2"/>
    <ControlledVocab accession="CSW:0000000073" category="DiagnosisCondition" value="Membranous nephropathy"/>
    <ControlledVocab accession="CSW:0000000074" category="DiagnosisCondition" value="Microscopic Polyangiitis"/>
    <ControlledVocab accession="CSW:0000000075" category="DiagnosisCondition" value="Multiple sclerosis"/>
    <ControlledVocab accession="CSW:0000000076" category="DiagnosisCondition" value="Obstructive uropathy"/>
    <ControlledVocab accession="CSW:0000000077" category="DiagnosisCondition" value="Polyarteritis Nodosa"/>
    <ControlledVocab accession="CSW:0000000078" category="DiagnosisCondition" value="Polymyalgia Rheumatica"/>
    <ControlledVocab accession="CSW:0000000079" category="DiagnosisCondition" value="Posterior urethral valves/Obstruction"/>
    <ControlledVocab accession="CSW:0000000080" category="DiagnosisCondition" value="Reflux Nephropathy"/>
    <ControlledVocab accession="CSW:0000000081" category="DiagnosisCondition" value="Rheumatoid arthritis"/>
    <ControlledVocab accession="CSW:0000000082" category="DiagnosisCondition" value="Schnitzler syndrome"/>
    <ControlledVocab accession="CSW:0000000083" category="DiagnosisCondition" value="Sjogren's syndrome"/>
    <ControlledVocab accession="CSW:0000000084" category="DiagnosisCondition" value="Systemic Lupus Erythematosus"/>
    <ControlledVocab accession="CSW:0000000085" category="DiagnosisCondition" value="Takayasu's Arteritis"/>
    <ControlledVocab accession="CSW:0000000086" category="DiagnosisCondition" value="Transplant"/>
    <ControlledVocab accession="CSW:0000000087" category="DiagnosisCondition" value="Trisomy 8"/>
    <ControlledVocab accession="CSW:0000000088" category="DiagnosisCondition" value="Ulcerative colitis"/>
    <ControlledVocab accession="CSW:0000000089" category="DiagnosisCondition" value="Urinary stone disease"/>
    <ControlledVocab accession="CSW:0000000090" category="DiagnosisCondition" value="Vasculitic Rash"/>
    <ControlledVocab accession="CSW:0000000092" category="DiagnosisCondition" value="Wegener's Granulomatosis"/>
    <ControlledVocab accession="CSW:0000000093" category="DiagnosisConfidence" value="Definite"/>
    <ControlledVocab accession="CSW:0000000094" category="DiagnosisConfidence" value="Possible"/>
    <ControlledVocab accession="CSW:0000000095" category="DiagnosisConfidence" value="Probable"/>
    <ControlledVocab accession="CSW:0000000096" category="DiseaseActivity" value="Active disease/Flare"/>
    <ControlledVocab accession="CSW:0000000097" category="DiseaseActivity" value="Low-grade activity"/>
    <ControlledVocab accession="CSW:0000000098" category="DiseaseActivity" value="No activity"/>
